In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("score.csv")

In [3]:
df.head()

   Age  Gender  Annual_Income  Spending_Score  Purchased
0   23    Male          32000              45          0
1   45  Female          64000              78          1
2   34    Male          58000              60          1
3   25  Female          35000              40          0
4   52    Male          72000              65          1

In [4]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Gender']=le.fit_transform(df['Gender'])

In [5]:
df

    Age  Gender  Annual_Income  Spending_Score  Purchased
0    23       1          32000              45          0
1    45       0          64000              78          1
2    34       1          58000              60          1
3    25       0          35000              40          0
4    52       1          72000              65          1
5    46       0          69000              70          1
6    29       1          42000              55          0
7    31       0          48000              58          0
8    27       1          39000              52          0
9    41       0          61000              66          1
10   36       1          54000              59          1
11   28       0          43000              54          0
12   33       1          50000              61          1
13   39       0          62000              63          1
14   22       1          30000              42          0
15   44       0          67000              71          1
16   37       1          56000              64          1
17   26       0          36000              47          0
18   30       1          47000              56          0
19   48       0          70000              74          1
20   35       1          52000              62          1
21   24       0          34000              44          0
22   40       1          60000              67          1
23   32       0          49000              57          0
24   38       1          55000              60          1
25   29       0          41000              50          0
26   43       1          65000              72          1
27   27       0          38000              48          0
28   34       0          53000              59          1
29   31       1          46000              55          0